### ISSUE TITLE
check all specs against reality & fix

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jsagent#1]
can someone validate 
https://github.com/Jumpscale/jsagent/blob/master/specs/jsagent.md
and tell me if everything is in 
please check word by word and whatever is not in code or change code or change spec
whatever is missing or different create issues for the milestone just defined or change spec

- does the agent run on windows & on linux
- is the statsd aggregation in the jsagent?
- is config format correct in spec
- what happens after statsd aggregation, how do we send to AC and how is it dealt with there?

**Comment by muhamadazmy** [comment]
Stats aggregation is indeed done inside the jsagent, only aggregated messages sent to the AC in a compact format.
For more details about the stats aggregator operation check the [wiki](https://github.com/Jumpscale/jsagent/wiki/Stats)

**Comment by muhamadazmy** [comment]
I have updated the specs to reflect the following:
- current  configuration syntax.
- highlighted the missing parts that aren't implemented (currently only 3 commands are missing `get_msgs`, `del_msgs`, and `get_process_stats`)
