### ISSUE TITLE
python client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jsagent#2]
create good documented python client
(documentation in methods)
using nothing but the redis queues

**Comment by grimpy** [comment]
Make sure we have a client for jumpscale (extension)

**Comment by muhamadazmy** [comment]
Done

**Comment by despiegk** [comment]
where is the client?

**Comment by muhamadazmy** [comment]
Code is at https://github.com/Jumpscale/jsagentcontroller/tree/master/client 
but you can simply install it like:

```bash
ays install -n jsagentcontroller_go_client
```

then can be accesses in js like

```python
client = j.clients.ac.Client()
```

**Comment by muhamadazmy** [comment]
https://github.com/Jumpscale/jsagent/wiki/AYS-Integration
