### ISSUE TITLE
think execute_js_lua & execute_js_py not implemented properly

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jsagent#22]
it should work with jumpscripts
jumpscript is identified by
- domain: domain of jumpscript (to do categorization)
- name: name of jumpscript or cmd to execute (will give all a name)

there is missing spec how to store them on AC, please add to spec
I guess best is to store them in redis 

jumpscripts/py/$domain__$name

**Comment by grimpy** [comment]
Currently jumpscripts are loaded from a specified path (configued in agent) and execute as command.
We will need to modify the specs to reflect it should be loaded from AC and AC stores it in redis.

**Comment by muhamadazmy** [comment]
Will be part of #25
