### ISSUE TITLE
ugly ays

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jsagent#27]
https://github.com/Jumpscale/ays_jumpscale7/blob/master/_jumpscale/jsagentcontroller_go/actions.py
this is bash in python
please create better version, check the other AYS as well

**Comment by muhamadazmy** [comment]
This was already copied from another AYS, I thought it's the official way
to to it. Will work on a better version.

**Comment by muhamadazmy** [comment]
Package refactoring is complete, but I currently can't test a full installation due to issues with contoml module that are still under progress

**Comment by muhamadazmy** [comment]
Fixed
