### ISSUE TITLE
When benchmarking jsagent crashed with too many open files

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/jsagent#28]
In [20]: client = acclient.Client()
In [21]: %timeit client.execute(1, 10, "hostname")

Crashed jsagent with

2015/07/22 22:13:49 Starting command b1aa27da-960f-42e5-87a3-bea69d58a1aa# execute hostname
2015/07/22 22:13:49 Failed to start process fork/exec /usr/bin/hostname: too many open files
2015/07/22 22:13:49 Starting command 8031665c-c90c-4ed4-8d25-9d66c4d2867b# execute hostname
2015/07/22 22:13:49 Failed to start process fork/exec /usr/bin/hostname: too many open files
2015/07/22 22:13:49 Starting command 691bb3e3-ed0c-426b-b852-9c8595369feb# execute hostname
2015/07/22 22:13:49 Failed to start process fork/exec /usr/bin/hostname: too many open files
2015/07/22 22:13:49 Starting command bd8f1af8-2dd4-49d2-a21f-a08d0139b9e1# execute hostname
2015/07/22 22:13:49 Failed to start process fork/exec /usr/bin/hostname: too many open files
2015/07/22 22:13:49 Starting command e7af9b9e-0261-446a-bbe7-f481df394909# execute hostname
2015/07/22 22:13:49 Failed to start process fork/exec /usr/bin/hostname: too many open files
2015/07/22 22:13:49 Starting command de943bb1-888d-4e96-88e2-93f94f6c840e# execute hostname
2015/07/22 22:13:49 Failed to start process fork/exec /usr/bin/hostname: too many open files
2015/07/22 22:13:49 process exited normally
2015/07/22 22:13:49 Exit status:  true
2015/07/22 22:13:49 process exited normally
2015/07/22 22:13:49 Exit status:  true
2015/07/22 22:13:49 process exited normally
2015/07/22 22:13:49 Exit status:  true
2015/07/22 22:13:50 process exited normally

Jobs get spawned async withouth limit so things start going bad

**Comment by grimpy** [comment]
Replacing hostname with something like sleep 5 will reproduce it easier

**Comment by muhamadazmy** [comment]
As discussed, this happens when we spawn lots and lots of subprocesses that exhaust the max number of open files. The solution should be that we apply a configurable limit on the max number of concurrent jobs.

**Comment by muhamadazmy** [comment]
Fixed, the max_jobs can be configured in the agent.toml .
