### ISSUE TITLE
Secure Agent communication with client certificates

### ISSUE THREAD

**Issue by muhamadazmy** [Jumpscale/jsagent#29]

**Comment by muhamadazmy** [comment]
Follow this instructions to set it up
https://github.com/Jumpscale/jsagent/wiki/Using-Client-Certificate-For-Security

**Comment by despiegk** [comment]
for debug purposes can the agent still work without security?
some setting somewhere

On Tue, Jul 28, 2015 at 1:42 PM, Muhamad Azmy <notifications@github.com>
wrote:

> Closed #29 <https://github.com/Jumpscale/jsagent/issues/29>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jsagent/issues/29#event-367121557>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
Yes it can, if the controller URL in the agent configuration uses HTTP instead of HTTPS, security and client certificate will not be used. Securing with client certificates can only be used  over https.
