### ISSUE TITLE
Role based agents

### ISSUE THREAD

**Issue by grimpy** [Jumpscale/jsagent#30]
A agent can assigne be assigned a set of roles.

When it connects to agentcontroller, agentcontroller will provide a job for the role specific stuff or node specifc stuff

**Comment by muhamadazmy** [comment]
Done, agents now can define a list of roles they can play.
https://github.com/Jumpscale/jsagent/wiki/agent-configuration#main

**Comment by muhamadazmy** [comment]
Need to add support to sorting the tasks based on gid/role combination, in that case only agents with that role and are part of this grid are allowed to process this task

**Comment by muhamadazmy** [comment]
Fixed

**Comment by despiegk** [comment]
is there documentation?

On Tue, Aug 4, 2015 at 1:30 PM, Muhamad Azmy <notifications@github.com>
wrote:

> Closed #30 <https://github.com/Jumpscale/jsagent/issues/30>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Jumpscale/jsagent/issues/30#event-372942250>.
>



-- 
------------------------
Kristof De Spiegeleer
+971525609014
+201206927877
+32 475405474
skype: despiegk

**Comment by muhamadazmy** [comment]
It's explained  briefly in the agent config page 
https://github.com/Jumpscale/jsagent/wiki/agent-configuration#main
