### ISSUE TITLE
driver for test scripts for MS1 (linux)

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jsagent#4]
create driver script for MS1 which runs the scripts

steps
- create machine on MS1 ubuntu 14.04
- install golang (over ssh) : @ys
- install redis: @ys
- build/install agent & ac: @ys
- deploy 3 more machines all with agent only which connect to ac
- run python test scripts to see all is working as it should

**Comment by muhamadazmy** [comment]
https://github.com/Jumpscale/jsagent/blob/master/tools/msdriver.py
