### ISSUE TITLE
document how to work with stats

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/jsagent#5]
- how do they get aggregated
- how do they get send to AC
- how do they get from AC into influxdb
- how to get realtime info from aggregator on AGENT e.g. want to know last avg for specific statistic

**Comment by muhamadazmy** [comment]
Please check [Stats wiki](https://github.com/Jumpscale/jsagent/wiki/Stats) for details about stats aggregator operations and behavior.

**Comment by despiegk** [comment]
this is not a correct implementation of statsd protocol
the client should NOT have to bother about avg, max, ...
we should support statsd format natively
https://github.com/etsy/statsd/blob/master/docs/metric_types.md#gauges
the aggregate just like statsd does
we have invented something new, that was not the goal

**Comment by muhamadazmy** [comment]
See #21

**Comment by despiegk** [comment]
there are golang clients 
https://github.com/quipo/statsd
